// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsbamxeeoagxdefcagta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzYmFteGVlb2FneGRlZmNhZ3RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTAwNDEsImV4cCI6MjA2OTQ2NjA0MX0.E8mXC2-MlD8aek0RODicqF6iNM2EvaFQVdcTK5vfn7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});